inherit_gem:
  jekyll: .rubocop.yml

require: rubocop-jekyll

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - script/**/*
    - vendor/**/*

Metrics/LineLength:
  Exclude:
    - jekyll_reading_time.gemspec
